# Generated by Django 3.0.7 on 2020-09-10 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('unitate_cazare', '0002_auto_20200910_2031'),
    ]

    operations = [
        migrations.CreateModel(
            name='PopularDestination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media', verbose_name='Image')),
                ('nume_judet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='unitate_cazare.Judete')),
            ],
        ),
    ]
