# Generated by Django 3.0.7 on 2020-09-10 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unitate_cazare', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unitatecazare',
            name='poza_prezentare',
            field=models.ImageField(upload_to='media'),
        ),
    ]
