# Generated by Django 3.0.7 on 2020-09-07 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unitate_cazare', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='judete',
            name='imagine_judet',
            field=models.ImageField(default=None, upload_to='media'),
        ),
    ]
